### ISSUE TITLE
Ground Unit RigidBody Movement gets Stuck Alot on Small Planets

### ISSUE THREAD

**Issue by valkyrienyanko** [Valks-Games/valks-game#5]
## Issue
Planets are not perfectly spherical, ground unit RigidBody getting stuck trying to go over elevated points on the surface of the planet.

I am aware of the lack of detail in this issue.

## Solution
The reason why we do not want to ditch RigidBodies entirely is because 1) nice gravity calculations and 2) units moving in groups should move apart from each other.

Instead of `rb.AddForce(...)` use `rb.MovePosition(...)`

Reserve `rb.AddForce(...)` for things like flying projectiles.

**Comment by JimmyRooster** [comment]
Hello,

Rigidbody gravity is not great for your project because it always goes in -Y which would make units on the bottom of the world fly off.

For pathfinding, it is quite possible to calculate multi agent paths without having physics (either just colliders or same simple maths). There are many articles on this https://www.aaai.org/ocs/index.php/SOCS/SOCS11/paper/viewFile/4039/4361 I also think it looks better if units are not crashing into each other.

Also having more than about a thousand rigidbodies along with the rest of a game can cause an unplayable FPS on some computers.

For things like projectiles, if you use unity physics you can get different results if you play the scene multiple times. This means the server will have to send constant updates for projectiles to sync everything nicely.

I'm interested to see what you think?
